# Generated by Django 3.2 on 2023-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
