# Generated by Django 3.2 on 2023-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
