# Generated by Django 3.2 on 2023-07-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_newsletter_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter_subscribed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
