# Generated by Django 3.2 on 2023-07-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('board_width', models.PositiveIntegerField()),
                ('board_height', models.PositiveIntegerField()),
                ('snake_body', models.TextField(default='')),
                ('food_position_row', models.PositiveIntegerField()),
                ('food_position_col', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.player')),
            ],
        ),
    ]
