# Generated by Django 3.2 on 2023-07-13 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_avatar_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snake', '0002_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='avatar_name',
        ),
        migrations.AddField(
            model_name='game',
            name='direction',
            field=models.CharField(default='right', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.avatar'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.player')),
            ],
        ),
    ]
