# Generated by Django 3.2 on 2023-07-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0004_delete_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='avatar',
        ),
    ]
