# Generated by Django 3.2 on 2023-07-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_player_name_avatar_avatar_name'),
        ('snake', '0005_remove_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.avatar'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
