# Generated by Django 3.2 on 2023-06-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_aggregate_rating_review_aggregaterating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='aggregaterating',
        ),
    ]
