# Generated by Django 3.2 on 2023-06-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230606_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='aggregate_rating',
            new_name='aggregaterating',
        ),
    ]
