# Generated by Django 3.2 on 2023-04-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
