# Generated by Django 3.2 on 2023-06-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='aggregate_rating',
        ),
    ]
