# Generated by Django 3.2 on 2023-06-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_rating_product_aggregate_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='aggregate_rating',
        ),
    ]
