# Generated by Django 3.2 on 2023-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_aggregate_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aggregaterating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
