# Generated by Django 3.2 on 2023-06-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_aggregaterating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='aggregaterating',
        ),
    ]
